name: GitHub Actions
on: [push]
jobs:
  precommit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install poetry
      - name: Activate venv
        run: poetry install
      - name: Run precommit
        run: poetry run pre-commit run --all

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cache node modules
        uses: actions/cache@v2
      - name: Run tests
        run: poetry run pytest --junitxml=junit/test-results-${{ matrix.python-version }}.xml --cov=python_project --cov-config=".coveragerc"
      - name: Upload pytest test results
        uses: actions/upload-artifact@v2
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml


#  Pages:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        python-version: [3.8 ]
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up Python ${{ matrix.python-version }}
#        uses: actions/setup-python@v2
#        with:
#          python-version: ${{ matrix.python-version }}
#      - name: Install dependencies
#        run: pip install poetry
#      - name: Activate venv
#        run: poetry install
#      - name: Build the book
#        run: poetry run jupyter-book build .
#      - name: GitHub Pages action
#        uses: peaceiris/actions-gh-pages@v3.6.1
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./_build/html


